
services:
  energy-model:
    build:
      context: ./energy-model
    container_name: ev_energy_model
    ports:
      - "8001:8001"
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: ev_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/data
    depends_on:
      - energy-model
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: ev_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
